# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 093d09cd981fe3f02c6bbfd72ca3ad023c0dd33764342cef7be4da9e5e8b865c99a6f7b58b61fbf152bc25887fcea00163c076b08059482c9988f127b3c052f7

test:
  secret_key_base: 943681804b2a5082de9d95cf80b0fb0bfd30bc27016ccf17564f4dc97bb3c71212c586b92235a61c11940712898a36e5009ac80e800eea6c6608059da55a3e6f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
